- name: ticket_automation
  module: agent_pm.plugins.ticket_automation:TicketAutomationPlugin
  enabled: true
  config:
    project_key: AGENT
    issue_type: Task
    summary_prefix: "[Plan]"
- name: feedback_collector
  module: agent_pm.plugins.feedback:FeedbackPlugin
  enabled: true
  config:
    storage_path: ./data/feedback.json
    route_prefix: /plugins/feedback
- name: slack_followup_alerts
  module: agent_pm.plugins.slack_notifications:SlackAlertsPlugin
  enabled: false
  config:
    channel: null
- name: warehouse_export
  module: agent_pm.plugins.warehouse_export:WarehouseExportPlugin
  enabled: false
  config:
    path: ./data/plugin_events.jsonl
